name: docker build
on:
  push:
    branches:
      - master

jobs:
  rtorrent:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@master
      - name: build
        uses: triptixx/action-docker-build@master
        with:
          repo: rtorrent-dev
          make: true
      - name: test
        uses: triptixx/action-docker-test@master
        with:
          verbose: true
          repo: rtorrent-dev
          exec_pre: nc -z 127.0.0.1 51578
      - name: publish
        uses: triptixx/action-docker-publish@master
        with:
          docker_username: ${{ secrets.docker_username }}
          docker_password: ${{ secrets.docker_password }}
          from: rtorrent-dev
          repo: ${{ secrets.docker_username }}/rtorrent
          tags: latest,%label org.label-schema.version | %auto
